### ISSUE TITLE
当我运行launch文件时，请问是什么问题，谢谢

### ISSUE THREAD

**Issue by davidlmljll** [AbangLZU/LaneNetRos#1]
NotFoundError (see above for traceback): Key lanenet_model/inference/decode/deconv_1/deconv_1/kernel not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor
_names, save/RestoreV2/shape_and_slices)]]

**Comment by AbangLZU** [comment]
the model and code from the original project is changed, see [lanenet-lane-detection](https://github.com/MaybeShewill-CV/lanenet-lane-detection) , I have update the code to support the new model, but there is still some problem in the line fitting part (the remap params should be modified). You can run the code, it should work now.

**Comment by Jeremy26** [comment]
It's still an error to me ! I have the new model and pulled the code today but I have the same error when restoring

```
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_1_fuse/fuse_conv/W not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```
